### ISSUE TITLE
how can you use this plugin?

### ISSUE THREAD

**Issue by pmario** [bengillies/tiddlybookmarklet#1]
how can you use this plugin?

**Comment by pmario** [comment]
Oh. I found it. It did install itself in the bottom of the screen. So it is not visible for toolbar adjustment.

**Comment by bengillies** [comment]
I agree it's an awkward default position, but I'm not sure there's anything I can do about it without diving into XUL (_shudder_). You can move it up into the to the toolbar manually if you wanted to though (right click and "customize"; then drag up to the toolbar).

**Comment by bengillies** [comment]
I should also point out, there are a few known bugs where occasionally it doesn't show up properly and you have to close it and click it again.

**Comment by pmario** [comment]
I do have a more serious problem. It automatically posts to my pmario space but I want to post to pmbm. So I'll stay with the old one for the moment.

**Comment by bengillies** [comment]
RIght ok, I'll need to think of a way to allow that to be configured.
