### ISSUE TITLE
with FF22 it only worked once

### ISSUE THREAD

**Issue by pmario** [bengillies/tiddlybookmarklet#2]
with FF22 it only worked once.

I did bookmark a github page for testing -> Everything worked.
Opening the widget again, just displays an empty grey background. 

Restarting FF doesn't fix the problem.

**Comment by bengillies** [comment]
Yeah this is a known problem. Not sure why this is happening yet.

As a workaround, you should be able to close and open it again though (i.e. click the button again to close it, wait a bit, then click again to open it). You may have to click inside the tab to focus it properly.

**Comment by pmario** [comment]
I did test the latest version, with the "save space config". FF 22
- select some text in a google group
- click the bookmark icon
- don't save, don't click any button
- click the bookmark icon again, to close it

After that, it won't show the form anymore. Close / Open FireFox "sometimes" fixes the problem.

**Comment by bengillies** [comment]
Yeah I haven't looked at that yet. I've been having problems isolating it to test properly. I'll update here again when it's fixed.
